tasks:
  - init: |
      sudo apt-get -yq install build-essential libreadline-dev zlib1g-dev flex bison libxml2-dev libxslt-dev libssl-dev libxml2-utils xsltproc ccache
      ./configure
      make
  - command: echo "let's start"